const unsigned int WINDOW_WIDTH{800};
const unsigned int WINDOW_HEIGHT{600};
const char* GAME_NAME{"Yggdrasil Quest"};
const char* ASSETS_SPRITES{"assets/sprites.png"};
const char* ASSETS_SPRITES_WALLS{"assets/dungeon_wall.png"};
const char* ASSETS_SPRITES_FLOOR{"assets/dungeon_floor.png"};
const char* ASSETS_SPRITES_DICE{"assets/dice.png"};
const char* ASSETS_DIALOGS_JSON{"assets/dialogs/level1.json"};
const char* ASSETS_ENEMIS_JSON{"assets/dialogs/enemies.json"};
const char* ASSETS_TILES{"assets/tiles.png"};
const char* ASSETS_SPRITES_UI{"assets/GUI/UI_elements.png"};
const char* ASSETS_SPRITES_BUTTON{"assets/GUI/button.png"};
const char* ASSETS_MAPS{"assets/maps/level1.grid"};
const char* ASSETS_FONT_ARCADECLASSIC{"assets/fonts/ARCADECLASSIC.ttf"};
const char* ASSETS_FONT_ANCIENT{"assets/fonts/AncientModernTales.ttf"};
const char* ASSETS_AUDIO_MAIN_MENU{"assets/audio/music/Blood Lord - Unwelcome Guests - 02 A Long Journey.ogg"};
const char* ASSETS_AUDIO_GAMEPLAY{"assets/audio/music/Blood Lord - Unwelcome Guests - 08 An Ancient Relic.ogg"};
